---
#
#  Actions common to all dbling crawler nodes
#
- hosts: crawlers
  vars:
    code_dir: /home/ubuntu/dbling2
    mgt_ip: 10.90.90.227
  remote_user: ubuntu

  tasks:
  #
  #  Graph Tool Repos
  #
  - name: add the apt key for graph-tool
    apt_key:
      keyserver: pgp.skewed.de
      id: 612DEFB798507F25
      state: present
    become: yes

  - name: add the first repo for graph-tool to apt
    apt_repository:
      repo: "deb http://downloads.skewed.de/apt/{{ ansible_lsb.codename }} {{ ansible_lsb.codename }} universe"
      state: present
      filename: graph-tool
      update_cache: no
    become: yes

  - name: add the second repo for graph-tool to apt
    apt_repository:
      repo: "deb-src http://downloads.skewed.de/apt/{{ ansible_lsb.codename }} {{ ansible_lsb.codename }} universe"
      state: present
      filename: graph-tool
      update_cache: no
    become: yes

  #
  #  General package installation
  #
  - name: update apt's cache
    apt:
      update_cache: yes
    become: yes

  - name: ensure required packages are at the latest version
    apt: name={{ item }} state=latest cache_valid_time=600
    with_items:
      - rsync
      - sendmail  # Required for email reports
      - python3
      - python3-pip
      - python3-mysql.connector
      - build-essential  # prereq for Python cryptography lib
      - libssl-dev  # prereq for Python cryptography lib
      - libffi-dev  # prereq for Python cryptography lib
      - python-dev  # prereq for Python cryptography lib
      - python3-graph-tool
    become: yes

  #
  #  Access control stuff 1
  #
  - name: ensure dbling is listed in /etc/hosts
    lineinfile:
      dest: /etc/hosts
      insertafter: '127\.0\.0\.1'
      state: present
      line: '{{ mgt_ip }}  dbling'
    become: yes

  - name: Create group "celery", needed by celery init scripts
    group:
      name: celery
      state: present
    become: yes

  - name: Create user "celery", needed by celery init scripts
    user:
      name: celery
      group: celery
      state: present
      createhome: no
    become: yes

  #
  #  Sync the code, install the libraries it uses
  #
  - name: ensure directory for the code exists
    file:
      dest: "{{ code_dir }}"
      state: directory
      owner: ubuntu
      group: celery
    become: yes

  - name: ensure directories for extensions exist
    file:
      dest: /var/lib/dbling
      state: directory
      owner: ubuntu
      group: ubuntu
    become: yes

  - name: sync the files in common
    synchronize:
      src: common
      dest: "{{ code_dir }}"
    register: sync_common

  - name: sync the files in crawl
    synchronize:
      src: crawl
      dest: "{{ code_dir }}"
    register: sync_crawl

  - name: sync the files in secret
    synchronize:
      src: secret
      dest: "{{ code_dir }}"
    register: sync_secret

  - name: ensure dir for dbling's logs exists
    file:
      dest: "{{ code_dir }}/log"
      state: directory
      group: celery
      owner: ubuntu
    become: yes

  - name: create crx log file that's writable by celery user
    copy:
      dest: "{{ code_dir }}/log/crx.log"
      content: ""
      force: no
      group: celery
      owner: ubuntu
      mode: 664
    become: yes

  - name: ensure dir for dbling's sitemaps exists
    file:
      dest: "{{ code_dir }}/crawl/sitemaps"
      state: directory
      group: celery
      owner: ubuntu
    become: yes

  - name: copy python libraries requirements file
    copy:
      src: requirements.txt
      dest: "{{ code_dir }}/requirements.txt"
    register: sync_reqs

  - name: install python libraries
    pip:
      executable: pip3
      requirements: "{{ code_dir }}/requirements.txt"
    become: yes

  #
  #  Access control stuff 2
  #
  - name: move ssh keys to ~/.ssh then copy pub key to authorized_keys and set proper permissions
    shell: mv dblings-key dblings-key.pub ~/.ssh/ && cat ~/.ssh/dblings-key.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/dblings-key ~/.ssh/authorized_keys
    args:
      chdir: "{{ code_dir }}/secret"
      creates: ~/.ssh/dblings-key

  - name: Empty the known_hosts file
    copy:
      dest: /home/ubuntu/.ssh/known_hosts
      content: ""
      mode: 0600



#
#  Actions for the crawler master
#
- hosts: crawl-masters
  remote_user: ubuntu

  tasks:
  - include_vars:
      file: 'secret/passes.yml'

  #
  #  Cinder Volume Setup
  #
  - name: Ensure Cinder volumes are mounted
    mount:
      state: mounted
      src: "{{ item.src }}"
      name: "{{ item.path }}" # As of Ansible 2.3, the "name" option has been changed to "path" as default, but "name" still works as well.
      fstype: ext4
      opts: defaults
      dump: 0
      passno: 2
    with_items:
      - { src: 'UUID=bee6c48f-f2e9-46ab-96a5-4669410f783c', path: '/var/lib/mysql' }
      - { src: 'UUID=9208c14a-6ce3-47f8-be9a-53731efdcfe3', path: '/var/lib/dbling' }
    become: yes

  #
  #  MySQL Setup and Configuration
  #
  - name: ensure mysql packages are at the latest version
    apt: name={{ item }} state=latest cache_valid_time=600
    with_items:
      - mysql-server
      - mysql-client
      - python3-mysqldb
    become: yes

  - name: set root password for MySQL
    mysql_user:
      name: root
      password: '{{ mysql_rt_pass }}'

  - name: drop file with new login for MySQL
    template:
      src: daemons/my.cnf
      dest: ~/.my.cnf
      mode: 0600

  - name: ensure the `chrome` database exists
    mysql_db:
      name: chrome
      state: present
    register: db_chrome

  - name: set up privileges for user 'dbling_dbusr'@'localhost'
    mysql_user:
      name: dbling_dbusr
      host: localhost
      password: '{{ mysql_dbling_pass }}'
      state: present
      priv: 'chrome.*:SELECT,INSERT,UPDATE,CREATE,ALTER'
    register: db_perm_local

  - name: set up privileges for user 'dbling_dbusr'@'10.90.%'
    mysql_user:
      name: dbling_dbusr
      host: '10.90.%'
      password: '{{ mysql_dbling_pass }}'
      state: present
      priv: 'chrome.*:SELECT,INSERT,UPDATE'
    register: db_perm_remote

  - name: bind MySQL to listen to all incoming connections
    lineinfile:
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      state: present
      line: 'bind-address            = *'
      regexp: 'bind-address.*'
    become: yes
    register: mysql_conf_changed

  - name: restart mysql if the configuration made any changes
    service:
      name: mysql
      state: restarted
    when: db_chrome.changed or db_perm_local.changed or db_perm_remote.changed or mysql_conf_changed.changed
    become: yes

  #
  #  RabbitMQ Setup and Configuration
  #
  - name: ensure rabbitmq-server is at the latest version
    apt:
      name: rabbitmq-server
      state: latest
      cache_valid_time: 600
    become: yes

  - name: enable RabbitMQ management console
    command: rabbitmq-plugins enable rabbitmq_management
    become: yes
    register: plugin_enabled_output

  - name: Checking if the RabbitMQ management console was already enabled, restarting rabbitmq-server if it wasn't
    service:
      name: rabbitmq-server
      state: restarted
    when: plugin_enabled_output.stdout.find('Plugin configuration has changed') != -1
    # The above string will appear in the output only when the console wasn't already enabled, so only in that case
    # do we need to restart RabbitMQ.

  #
  #  Celery beat service setup and configuration
  #
  - name: check if celerybeat service already exists
    shell: service --status-all | grep celerybeat || echo ""
    register: celerybeat_check

  - name: copy beat daemon script to /etc/init.d/
    copy:
      src: daemons/celerybeat
      dest: /etc/init.d/celerybeat
      owner: root
      group: root
      mode: 0755
    become: yes
    register: sync_celerybeat_d

  - name: copy beat daemon config to /etc/default/
    copy:
      src: daemons/celerybeat.conf
      dest: /etc/default/celerybeat
      owner: root
      group: root
      mode: 0644
    become: yes
    register: sync_celerybeat_conf

  - name: reload systemctl units
    command: systemctl daemon-reload
    become: yes
    when: sync_celerybeat_d.changed or sync_celerybeat_conf.changed or sync_common.changed or sync_crawl.changed or
          sync_secret.changed or sync_reqs.changed
    register: service_systemctl_restarted

  - name: restart celerybeat if the configuration changed (service already exists)
    service:
      name: celerybeat
      enabled: yes
      state: restarted
    become: yes
    when: service_systemctl_restarted.changed and celerybeat_check.stdout.find('celery') != -1
    register: service_celerybeat_restarted

  - name: ensure the celerybeat service starts
    service:
      name: celerybeat
      enabled: yes
      state: started
    become: yes
    when: not service_celerybeat_restarted.changed



#
#  Actions for the crawler workers
#
- hosts: crawl-workers
  remote_user: ubuntu

  tasks:
  - name: ensure sshfs, upstart, and fuse are at latest version
    apt: name={{ item }} state=latest cache_valid_time=600
    with_items:
      - sshfs
      - upstart
      - fuse
    become: yes

  - name: configure fuse to allow other users to access the remote directory
    lineinfile:
      dest: /etc/fuse.conf
      state: present
      regexp: '^#?user_allow_other'
      line: 'user_allow_other'
    become: yes

  - name: copy sshfs configuration
    copy:
      src: daemons/crawler-sshfs.service
      dest: /etc/systemd/system/crawler-sshfs.service
      owner: root
      group: root
      mode: 0644
    become: yes

  - name: enable and start sshfs service
    systemd:
      daemon_reload: yes
      name: crawler-sshfs.service
      enabled: yes
      state: started
    become: yes

  - name: check if celeryd service already exists
    shell: service --status-all | grep celeryd || echo ""
    register: celeryd_check

  - name: copy worker daemon script to /etc/init.d/
    copy:
      src: daemons/celeryd
      dest: /etc/init.d/celeryd
      owner: root
      group: root
      mode: 0755
    become: yes
    register: sync_celery_d

  - name: copy worker daemon config to /etc/default/
    copy:
      src: daemons/celeryd.conf
      dest: /etc/default/celeryd
      owner: root
      group: root
      mode: 0644
    become: yes
    register: sync_celery_conf

  - name: restart celeryd if configurations or files changed (service already exists)
    service:
      name: celeryd
      state: restarted
    become: yes
    when: (sync_celery_d.changed or sync_celery_conf.changed or sync_common.changed or sync_crawl.changed or
           sync_secret.changed or sync_reqs.changed) and celeryd_check.stdout.find('celery') != -1
    register: service_celeryd

  - name: ensure celeryd service is started
    service:
      name: celeryd
      enabled: yes
      state: started
    become: yes
    when: not service_celeryd.changed
